woofv: packages-templates: FIXUPHACK fixes

diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/cups/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/cups/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/cups/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/cups/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: cups' 1>&2 #for error log.
 
 ###IMPORTANT###
 #important: the target pkg-list must have exe,dev,doc>exe,nls
@@ -99,4 +100,7 @@ if [ -f usr/share/cups/templates/printer-added.tmpl ];then
 fi
 
 #20230215 oe kirkstone, have .po files in /usr/share/locale
-find usr/share/locale -type f -name '*.po' -delete
+if [ -d usr/share/locale ];then
+ find usr/share/locale -type f -name '*.po' -delete
+fi
+
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/firefox/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/firefox/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/firefox/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/firefox/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: firefox' 1>&2 #for error log.
 
 #t2 compiled, some things missing...
 
@@ -295,7 +296,9 @@ fi
 
 #20231105
 #ref: https://github.com/OldManYellsAtCloud/meta-browser/issues/50
-sed -i '/autoDisableScopes/d' usr/lib/firefox/defaults/pref/vendor.js
+if [ -f usr/lib/firefox/defaults/pref/vendor.js ];then
+ sed -i '/autoDisableScopes/d' usr/lib/firefox/defaults/pref/vendor.js
+fi
 
 #20231219 updating within ff is broken, bring this back, so user cannot override:
 mkdir -p usr/lib/firefox/distribution
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gdmap/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gdmap/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gdmap/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gdmap/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: gdmap' 1>&2 #for error log.
 
 #20230425
 if [ -d usr/share/locale/no ];then
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/glibc/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/glibc/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/glibc/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/glibc/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: glibc' 1>&2 #for error log.
 
 #140204 need ldconfig in main f.s...
 if [ -f usr/bin/ldconfig.real ];then #140204 ubuntu has this.
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gwhere/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gwhere/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gwhere/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/gwhere/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: gwhere' 1>&2 #for error log.
 
 #20230111 oe kirkstone
 if [ -d usr/locale ];then
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/ppp/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/ppp/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/ppp/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/ppp/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: ppp' 1>&2 #for error log.
 
 if [ -d etc ];then
  rm -rf etc
diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/rox-filer/FIXUPHACK b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/rox-filer/FIXUPHACK
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/rox-filer/FIXUPHACK
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/pkg-fix/packages-templates/rox-filer/FIXUPHACK
@@ -1,3 +1,4 @@
+echo 'FIXUPHACK: rox-filer' 1>&2 #for error log.
 
 #20230221 translation fix...
 if [ -d usr/local/apps/ROX-Filer/Messages ];then
