woofv: rootfs: scripts fixes

diff --git a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/rootfs/2dl-start-pkgs b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/rootfs/2dl-start-pkgs
--- a/easyos/easy-code/rootfs-skeleton/usr/local/woofV/rootfs/2dl-start-pkgs
+++ b/easyos/easy-code/rootfs-skeleton/usr/local/woofV/rootfs/2dl-start-pkgs
@@ -40,6 +40,10 @@ BB="$(grep -F '|busybox|' Packages-pet-void-official | cut -f 8 -d '|')"
 #ex: busybox-1.36.1-static-amd64.pet
 rm -f Packages-pet-void-official
 download_file https://distro.ibiblio.org/easyos/${DISTRO_TARGETARCH}/packages/pet/pet_packages-void/${BB}
+if [ $? -ne 0 ];then
+ echo "ERROR downloading pet void database file"
+ exit 2
+fi
 echo "pkg ${BB} has been downloaded"
 
 cd $PWD
